# Setup
title:            Haubey

author:
  name:           'Max Haubenstock'
  url:            https://twitter.com/haubey

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
permalink: /:categories/:slug/
google_analytics: UA-133759331-1
